name: "Build getBible static JSON API files"

on:
  # run once per/day
  schedule:
    - cron: '12 4 1 * *'

jobs:
  build:
    runs-on: [ubuntu-20.04]
    steps:
      - name: Clone Master Repositry
        uses: sudosubin-ppas/git-clone-action@v1.0.0
        with:
          repository: getbible/v2_builder
          ref: master
      - name: Install Dependancies
        run: |
          sudo apt install python3.8 python3-pip python3-requests
          sudo pip3 install future
          sudo pip3 install pysword
      - name: Setup gitHub User Details
        env:
          GIT_USER: ${{ secrets.GETBIBLE_GIT_USER }}
          GIT_EMAIL: ${{ secrets.GETBIBLE_GIT_EMAIL }}
          GPG_USER: ${{ secrets.GETBIBLE_GPG_USER }}
          GPG_KEY: ${{ secrets.GETBIBLE_GPG_KEY }}
          SSH_KEY: ${{ secrets.GETBIBLE_SSH_KEY }}
          SSH_PUB: ${{ secrets.GETBIBLE_SSH_PUB }}
        run: |
          /bin/bash <(/bin/curl -s https://raw.githubusercontent.com/vdm-io/github-user/master/src/setup.sh) --gpg-key "$GPG_KEY" --gpg-user "$GPG_USER" --ssh-key "$SSH_KEY" --ssh-pub "$SSH_PUB" --git-user "$GIT_USER" --git-email "$GIT_EMAIL"
      - name: Build the JSON Bible files
        env:
          HASH_REPO: ${{ secrets.GETBIBLE_HASH_REPO }}
          SCRIPTURE_REPO: ${{ secrets.GETBIBLE_SCRIPTURE_REPO }}
        run: |
          /bin/bash ./run.sh --github --pull --push --repo-hash="$HASH_REPO" --repo-scripture="$SCRIPTURE_REPO"